tukio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


from accounts.views import (register_view, login_view, logout_view)
from tukiogram.views import IndexView

urlpatterns = [
    url(r'^$', IndexView, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^register', register_view, name='register'),
    url(r'^login', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    url(r'^api/', include('tukiogram.api.urls')),
    url(r'^', TemplateView.as_view(template_name='admin.html'))
]

accounts/models.py
from __future__ import unicode_literals

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.gis.db import models
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(_('email address'), unique=True)
	first_name = models.CharField(_('first name'), max_length=30, blank=True)
	last_name = models.CharField(_('last name'), max_length=30, blank=True)
	default_location = models.PointField(srid=4326, null=True, blank=True)
	date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
	is_active = models.BooleanField(_('active'), default=True)
	is_admin = models.BooleanField(default=False)
	avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
	is_verified = models.BooleanField(default=False)
	#timestamp as per coding4enterpreneurs
	#timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	#category = models.CharField(max_length=30)
	
	objects = UserManager()
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []
	
	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('users')
	
	def get_full_name(self):
		'''
		Returns the first_name plus the last_name, with a space in between.
		'''
		full_name = '%s %s' % (self.first_name, self.last_name)
		return full_name.strip()
	
	def get_short_name(self):
		'''
		Returns the short name for the user.
		'''
		return self.first_name
	
	@property
	def is_staff(self):
		"Is the user a member of staff?"
		# Simplest possible answer: All admins are staff
		return self.is_admin
	
	def email_user(self, subject, message, from_email=None, **kwargs):
		'''
		Sends an email to this User.
		'''
		send_mail(subject, message, from_email, [self.email], **kwargs)

tukiogram/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.gis.db import models


# Create your models here.

class Tukio(models.Model):
    CATEGORY_CHOICES = (
        ('corruption', 'Corruption'),
        ('robbery', 'Robbery'),
        ('vandalism', 'Vandalism'),
        ('burglary', 'Burglary'),
        ('drugUse', 'Drug Use'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    desc = models.CharField(max_length=70)
    timestamp = models.DateTimeField(auto_now_add=True)
    location_name = models.CharField(max_length=100, null=True, blank=True)
    location_geom = models.PointField(srid=4326, unique=True)

    def __unicode__(self):
        return self.desc

    def get_absolute_ulr(self):
        return self.desc


class Station(models.Model):
    name = models.CharField(max_length=50)
    location_geom = models.PointField(srid=4326, unique=True)
    helpline = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

    def get_absolute_ulr(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth import (
	authenticate,
	get_user_model,
)

User = get_user_model()


class UserLoginForm(forms.Form):
	email = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	
	def clean(self, *args, **kwargs):
		email = self.cleaned_data.get("email")
		password = self.cleaned_data.get("password")
		
		# user_qs = User.objects.filter(username=username)
		# if user_qs.count() == 1:
		#     user = user_qs.first()
		if email and password:
			user = authenticate(username=email, password=password)
			if not user:
				raise forms.ValidationError("This user does not exist")
			if not user.check_password(password):
				raise forms.ValidationError("Incorrect passsword")
			if not user.is_active:
				raise forms.ValidationError("This user is not longer active.")
		return super(UserLoginForm, self).clean()


class UserRegisterForm(forms.ModelForm):
	email = forms.EmailField(label='Email address')
	email2 = forms.EmailField(label='Confirm Email')
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = [
			'first_name',
			'last_name',
			'email',
			'email2',
			'password'
		]
	
	# def clean(self, *args, **kwargs):
	#     email = self.cleaned_data.get('email')
	#     email2 = self.cleaned_data.get('email2')
	#     if email != email2:
	#         raise forms.ValidationError("Emails must match")
	#     email_qs = User.objects.filter(email=email)
	#     if email_qs.exists():
	#         raise forms.ValidationError("This email has already been registered")
	
	#     return super(UserRegisterForm,self).clean(*args, **kwargs)
	
	def clean_email2(self):
		email = self.cleaned_data.get('email')
		email2 = self.cleaned_data.get('email2')
		if email != email2:
			raise forms.ValidationError("Emails must match")
		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("This email has already been registered")
		return email

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#000000"> {% block meta-desc %}
    <meta name="description" content="Know what is happening around you on Tukiogram. Tell people about an event happening at some location or post an alert incase of anything.On a map."> {% endblock meta-desc %}
    <title>The Samaritan | at your beck and call</title>
    <link rel="icon" type="image/png" href="/static/img/favicon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/MarkerCluster.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/L.Icon.Pulse.css">
</head>

<body>
    <header id="header" role="banner">
        <div id="nav-cont" class="container-fluid">
            <div id="navbar" class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand logo"><span class="logo_t">The</span><span
                        class="logo_g"> Samaritan</span></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                       <!-- <li>
                            <a href="/notifications"><span class="notification add-new">Notifications</span></a>
                        </li>
                        <li>
                            <a href="/profile"><span class="profile">Profile</span></a>
                        </li> -->
                        <li>
                            <a href="/logout"><span class="logout">Logout</span></a>
                        </li>
                        {% else %}
                        <li>
                            <a href="/register"><span class="notification add-new">Sign Up</span></a>
                        </li>
                        <li>
                            <a href="/login"><span class="notification add-new">Log In</span></a>
                        </li>
                        {% endif %}
                        <li>
                            <form class="navbar-form navbar">
                                <input type="text" class="form-control" placeholder="Search by Location" name="search-loc" id="srch-term">
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>{% block page-content %}
    <div id="container">
        <div id="tukio-homemap"></div>
        {% if user.is_authenticated %}
        <div class="leaflet-bottom leaflet-left leaflet-add-tukio">
            <button type="button" title="Add a tukio" class="btn btn-default btn-xs  add-button"><img src="/static/img/new_tukio.png"></button>
        </div>
        <div id="add-help" class="leaflet-bottom leaflet-left leaflet-add-help">
            <h4>Click at the location to add..</h4>
        </div>
        {% else %}
        <div class="leaflet-bottom leaflet-left leaflet-add-tukio">
            <h4 class="login-to-add"><a href="/login">Login </a>to report</h4>
        </div>
        {% endif %}
    </div>
    <div id="postModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                {% if user.is_authenticated %}
                <div class="modal-header">
                    <button type="button" class="close tukio-cancel-form" data-dismiss="modal" aria-hidden="true">×
                    </button>
                    What is happening here {{ user.first_name }}? Nearest Police Hotline: 999
                </div>
                <div class="modal-body">
                    <form class="form center-block tukio-form">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_category">What category is the incident?
                                <!-- <small>Alerts appear in red.</small> -->
                            </label>
                            <select class="form-control" id="id_category" name="category" required>
                                <option value="" selected="selected">---------</option>
                                <option value="corruption">Corruption</option>
                                <option value="robbery">Robbery</option>
                                <option value="burglary">Burglary</option>
                                <option value="vandalism">Vandalism</option>
                                <option value="drugUse">Drug use or dealing</option>
                            </select>
                        </div>
                        <input type="hidden" name="user" value="{{ user.id }}">
                        <input id="location_geom" type="hidden" name="location_geom" value="">
                        <div class="form-group">
                            <textarea class="form-control input-lg" maxlength="70" autofocus="" placeholder="Short description of the incident.." name="desc" required></textarea>
                        </div>
                        <div class="modal-footer">
                            <div>
                                <button class="btn btn-danger btn-sm tukio-cancel-form" aria-hidden="true">Cancel
                                </button>
                                <input type='submit' class='btn btn-info btn-sm' value='Post' />
                            </div>
                        </div>
                    </form>
                </div>
                {% else %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    Sign In
                </div>
                <div class="modal-body">
                    <h5>You need to be signed in to post report</h5>
                </div>
                <div class="modal-footer">
                    <div>
                        <a class="btn btn-info" href="/login" role="button">Sign In</a>
                        <ul class="pull-left list-inline">
                            <li><a href="/register">New here ? Register</a></li>
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock page-content %}
    <script type="text/javascript">
        // (function () {window.user = {{user|safe}};})();
    </script>
    <script src="https://code.jquery.com/jquery-3.2.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.5/leaflet.markercluster.js"></script>
    <script src="/static/js/L.Control.Locate.min.js"></script>
    <script src="/static/js/leaflet.spin.min.js"></script>
    <script src="/static/js/L.Icon.Pulse.js"></script>
    <script src="/static/js/app.js"></script>
</body>

</html>

templates/form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}



{% block meta-desc %}
    {% if title == 'Login' %}
        <meta name="description" content="Log into The Samaritan to report crime immediately you see it">
    {% else %}
        <meta name="description"
              content="Create a Samaritan account and help catch criminals">
    {% endif %}
{% endblock meta-desc %}

{% block page-content %}
    {% if title == 'Login' %}
        <div class="reglog-container">
            <div class='col-sm-6 col-sm-offset-3 register'>
                <h3>{{ title }}</h3>
                <hr/>
                <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <input type='submit' class='btn btn-info' value='{{ title }}'/> <span> <h5>New here? <a
                            href="/register">Register with ID or Passport number </a></h5> </span>
                </form>
            </div>
        </div>
    {% else %}
        <div class="reglog-container container">
            <div class="row">
                <form method='POST' action='' enctype='multipart/form-data' class="form-horizontal">{% csrf_token %}
                    <fieldset>
                        <!-- Form Name -->
                        <legend>Register</legend>
                        <!-- Text input-->
                        <div class="form-group">
                            {{ form.non_field_errors }}
                            <label class="col-md-4 control-label" for="id_first_name">Your ID/Passport number</label>
                            <div class="col-md-4">
                                <input id="id_first_name" name="first_name" placeholder="Your ID/Passport number"
                                       class="form-control input-md" maxlength="300" type="text" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label" for="id_last_name">Your phone number</label>
                            <div class="col-md-4">
                                <input id="id_last_name" name="last_name" placeholder="Your phone number"
                                       class="form-control input-md" maxlength="30" type="text" required>
                            </div>
                        </div>
                        <!-- Text input-->
                        <div class="form-group">


                            <label class="col-md-4 control-label" for="id_email"> Your email</label>
                            <div class="col-md-4">
                                <input id="id_email" name="email" placeholder="Your email"
                                       class="form-control input-md" type="email" required>
                                <span class="help-block">  {{ form.email.errors }} </span>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">

                            <label class="col-md-4 control-label" for="id_email2">Confirm Email</label>

                            <div class="col-md-4">
                                <input id="id_email2" name="email2" placeholder="Confirm Email"
                                       class="form-control input-md" type="email" required>
                                <span class="help-block">  {{ form.email2.errors }} </span>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="id_password">Password(</label>
                            <div class="col-md-4">
                                <input id="id_password" name="password" placeholder="Password"
                                       class="form-control input-md" type="password" required>
                                <span class="help-block"> {{ form.password.errors }} </span>
                            </div>
                        </div>

                        <!-- Button -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="singlebutton"> </label>
                            <div class="col-md-4">
                                <input type='submit' class='btn btn-info' value='{{ title }}'/>
                            </div>
                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    {% endif %}
{% endblock page-content %}

templates/index.html
{% extends 'base.html' %}
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-84661957-2', 'auto');
    ga('send', 'pageview');

</script>

templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head>
<body>
<div class="row login-wrapper row-centered">
{#    <div class="col-xs-12 login-box col-centered col-fixed"></div>#}
</div>
</body>
</html>